version: '2'
services:
  db:
    image: postgres
  web:
    tty: true
    stdin_open: true
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - ./app:/myapp/app
      - ./config:/myapp/config
      - ./db:/myapp/db
    ports:
      - "8000:8000"
    depends_on:
      - db
